### PR TITLE
Fix patch rejection

### PR DESCRIPTION
**Pull request by kaziu687**

### CODE REVIEW

**Comment by Viktor-KN** [comment]
Its already fixed..

**Comment by kaziu687** [comment]
There were two rejections in that file.

**Comment by Dream-Master** [comment]
@Viktor-KN schould we merge this or quit the pull ?

**Comment by Viktor-KN** [comment]
Just quit it. It was already fixed and builds fine. So I don't know what @kaziu687 is talking about.

**Pull request closed without merging**
